### ISSUE TITLE
using docker-for-windows fails

### ISSUE THREAD

**Issue by ATGardner** [maplethorpej/packstack#21]
The volume mapping for the postgresql fails on Windows due to a user permission issue.
Also - make sure .sh file EOL doesn't get messed up by Windows

**Comment by Callisto13** [comment]
Is this issue closable?

**Comment by ATGardner** [comment]
I think my PR handled the issue, yeah.

**Comment by Callisto13** [comment]
Cool, do you have the power to hit close?

**Comment by ATGardner** [comment]
Let's see if this works :-)

**Comment by ATGardner** [comment]
Are you taking over the repo? Do you plan on adding new features to it?

**Comment by Callisto13** [comment]
> Are you taking over the repo?

No :) Unless I am asked to help out, but the project is not mine.

> Do you plan on adding new features to it?

I have submitted some things and am already working on others. It is easier to discover new work if old or done issues are closed, so that is why I am helping out a little by clearing/checking in on stuff.

**Comment by ATGardner** [comment]
seems nice. I hope the original maintainer will actually approve and merge all the PRs that seem to be currently ready.
Thanks for putting in the effort.
