### ISSUE TITLE
Email / password based login

### ISSUE THREAD

**Issue by ewal** [maplethorpej/packstack#26]
Hi,
Just a feature request to use email instead of username for login credentials. I lost my username and can no longer use the service :)

**Comment by rammsteini** [comment]
Same here. I once used my email as username, then changed to a username which I forgot.
You also could write the username in the "Reset Password" email.

**Comment by ewal** [comment]
> Same here. I once used my email as username, then changed to a username which I forgot.
> You also could write the username in the "Reset Password" email.

Thanks 👍
