### ISSUE TITLE
Add "Big 3" weight breakdown category

### ISSUE THREAD

**Issue by maplethorpej** [maplethorpej/packstack#68]
We could easily combine the weights of the default categories Pack, Sleep System and Shelter System to generate this metric.

User request:

I’d love to be able to flag my “core 3” (pack/shelter/bedding) so they appear in the weight breakdown summary as a separate grouping, just like “worn weight” and “consumables”.

**Comment by Callisto13** [comment]
Should the be re-opened now the feature is gone in the new UI?
